### ISSUE TITLE
What is the use of configPath?

### ISSUE THREAD

**Issue by mittalyashu** [emilgoldsmith/stylelint-custom-processor-loader#48]

**Comment by emilgoldsmith** [comment]
See the README: https://github.com/emilgoldsmith/stylelint-custom-processor-loader#configpath

**Comment by mittalyashu** [comment]
Yeh, I have read that, but still it is unclear.

**Comment by emilgoldsmith** [comment]
If you don't have your stylelint in one of these places: https://stylelint.io/user-guide/configuration/#loading-the-configuration-object then you need to tell the loader where it is, that's what the option is for, usually it is not needed. If you feel the documentation could be clearer please feel free to submit a PR with updates
