### ISSUE TITLE
Cannot find module 'stylelint'

### ISSUE THREAD

**Issue by mittalyashu** [emilgoldsmith/stylelint-custom-processor-loader#49]
Getting this error in console.
![image](https://user-images.githubusercontent.com/29014463/37252762-fe70bdb8-254c-11e8-88f1-e4e7845215c2.png)

**Comment by emilgoldsmith** [comment]
Did you install stylelint?

**Comment by mittalyashu** [comment]
No. Do I need to install `stylelint` package to make this loader work?

**Comment by emilgoldsmith** [comment]
Yes, as you can see it is a peer dependency in the `package.json` and it should be pretty obvious since it is just a development tool to connect webpack and stylelint together.

If you think it could be clearer you could submit a PR that adds it to the README installation part
