### ISSUE TITLE
Option to keep webpack build alive on error

### ISSUE THREAD

**Issue by ugrupp** [emilgoldsmith/stylelint-custom-processor-loader#51]
Hey,
is there any way to keep the webpack build alive, even if a stylelint error has been thrown?

In https://www.npmjs.com/package/stylelint-webpack-plugin there's an option `emitErrors` which I believe turns errors into warnings, allowing the webpack build to finish.

Maybe I'm missing something here, but I think this could be very helpful.

**Comment by emilgoldsmith** [comment]
I think you'd call it `emitWarnings` instead and yeah I know the eslint-loader has something similar, it'd be a oneliner to implement so feel free to make a PR! You'd literally just have to put an `|| options.emitWarnings` in [here](https://github.com/emilgoldsmith/stylelint-custom-processor-loader/blob/7fb550fa8ad7ec9ccb19145600b00e99efac5891/index.js#L49-L53)

**Comment by emilgoldsmith** [comment]
And if you do it I would conform to the same option spec as [eslint](https://github.com/webpack-contrib/eslint-loader#errors-and-warning) for consistency

**Comment by ugrupp** [comment]
Done :)
