### ISSUE TITLE
Incorrect configPath resolution

### ISSUE THREAD

**Issue by harrysolovay** [emilgoldsmith/stylelint-custom-processor-loader#64]
I'm adding the `stylelint-custom-processor-loader` to my webpack configuration via a function that takes in the `configPath`. When I log out the value being passed in, it properly displays the following:

`/Users/harrysolovay/Desktop/rescripts/packages/examples/basic/.stylelintrc`

Still, I'm get the following compilation error:

`
Error: ENOENT: no such file or directory, open '/Users/harrysolovay/Desktop/rescripts/packages/examples/.stylelintrc'
`

It's deleting `basic/` from the path. What's goin' on with the `configPath`'s resolution?

Thanks!

**Comment by emilgoldsmith** [comment]
Fixed in #65
